language: php
sudo: required

cache:
    directories:
        - vendor
        - $HOME/.composer/cache
        - .travis/downloads
        - .travis/ffmpeg-release-64bit-static

before_install:
  - |
    if [ "x$XDEBUG" != "xyes" ]; then
      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || true
    fi
  - |
    if [ "x$INSTALL_FFMPEG" == "xyes" ]; then
      .travis/travis-install-ffmpeg.sh
    fi

install:
  - |
    if [[ $DEPS == 'lowest' ]]; then
      travis_retry composer -n update --prefer-dist --prefer-lowest --prefer-stable --no-interaction $COMPOSER_ARGS;
    else
      travis_retry composer -n update --prefer-dist --no-interaction $COMPOSER_ARGS;
    fi
jobs:
  allow_failures:
    - php: nightly
    - stage: Mutation (unit tests only)
    - stage: Make doc

  include:
    - stage: Tests and Coverage (PHP 7.3)
      php: 7.3
      env: XDEBUG=yes INSTALL_FFMPEG=yes
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml --coverage-clover=coverage.xml
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        - bash <(curl -s https://codecov.io/bash)
    - stage: PHPStan and Code style
      php: 7.2
      script:
        - composer phpstan
        - composer cs-check
    - stage: Test PHP7.1
      php: 7.1
      env: INSTALL_FFMPEG=yes
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml
    - stage: Test PHP7.2
      php: 7.2
      env: INSTALL_FFMPEG=yes
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml
    - stage: Test PHP7.1 With lowest deps
      php: 7.1
      env: INSTALL_FFMPEG=yes DEPS=lowest
      script:
        - ./vendor/bin/phpunit -v -c .travis/phpunit.xml
    - stage: Make doc
      language: python
      script:
        - sudo -H pip install --upgrade pip
        - sudo -H pip install -r ./requirements.txt
        - mkdocs build
    - stage: Mutation (unit tests only)
      php: 7.2
      env: XDEBUG=yes
      script:
        - ./vendor/bin/infection --configuration=./infection.json --test-framework=phpunit --test-framework-options='--testsuite=unit' --min-msi=40 --min-covered-msi=60 --threads=4
    - stage: Test PHP Nightly (unit tests only)
      php: nightly
      env: COMPOSER_ARGS=--ignore-platform-reqs
      script:
        - ./vendor/bin/phpunit --testsuite unit -v -c .travis/phpunit.xml

