site_name: 'Mediatools'
site_description: 'soluble-mediatools documentation'
site_author: 'Sébastien Vanvelthem'
site_url: https://soluble-io.github.io/soluble-mediatools

# Repository
repo_name: 'soluble-mediatools'
repo_url: 'https://github.com/soluble-io/soluble-mediatools'

# Copyright
copyright: 'Copyright &copy; 2018 Sébastien Vanvelthem'

strict: true

docs_dir: docs
site_dir: build/docs

nav:
    - Home:
      - Introduction: index.md
      - Features: service-overview.md
      - Installation: install.md
      - License: 'about/license.md'
    - Video services:
      - 'InfoReader': 'video-info-service.md'
      - 'Converter': 'video-conversion-service.md'
      - 'ThumbGenerator': 'video-thumb-service.md'
      - 'Analyzer': 'video-detection-service.md'
      - 'Notes':
        - 'Video filters': 'video-filters.md'
    - Notes:
      - 'Install':
        - FFMpeg: 'install-ffmpeg.md'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'deep-orange'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'play_circle_outline'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/soluble-io/soluble-mediatools'

extra_css:
  - 'assets/css/extra.css'
  - 'assets/css/monokai.css'

#google_analytics:
  #- ''
  #- 'auto'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
#      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
